version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html
     source: /
     destination: /usr/share/tomcat8/webapp
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: tomcat
     group: tomcat
     mode: 755
     type:
       - file
