version: 0.0
os: linux
files:
   - source: /
     destination: /var/lib/tomcat8/webapps
hooks:
   ApplicationStop:
     - location: scripts/stop.sh
   AfterInstall:
     -location: script/copywar.sh
   ApplicationStart:
   - location: scripts/start.sh
