version: 0.0
os: linux
files:
   - source: /
     destination: /var/lib/tomcat8/webapps
hooks:
  BeforeInstall:
    - location: sudo service tomcat8 stop
      runas : root
  AfterInstall:
    - location: sudo service tomcat8 start
      runas : root
